import type {Metadata} from 'next'
import Providers from "@/helpers/providers";
import GlobalStyles from '@/styles/global';
import theme from '@/styles/theme';

import {ThemeProvider} from 'styled-components';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Providers>
            <GlobalStyles />
            {children}
        </Providers>
        </body>
        </html>
    )
}
